name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    environment: Variables
    steps:
      - name: Checkout sourcecode 
        uses: actions/checkout@v3
      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      - name: Build and push docker containers
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "GRAALVM_DOCKER_IMAGE=${{ env.GRAALVM_DOCKER_IMAGE }}"
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
      - name: Sync readme.md to docker hub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          readme: "./README.md"
